Yaroslav Pashchenko ДЗ-1B
yaphystech/MIPT_DIHT pull request #6
Opened 2019-04-08 08:38 UTC by yaphystech

https://contest.yandex.ru/contest/11884/run-report/19497781/

2019-04-08 11:23 UTC, ibulgakov requested changes

2019-04-08 11:23 UTC, ibulgakov commented on B.cpp
>      int mincycle = MainDFS(graph);
FindMinCycle

2019-04-08 11:23 UTC, ibulgakov commented on B.cpp
>  int MainDFS(ListGraph& g) {
ссылка лучше константная

2019-04-08 11:23 UTC, ibulgakov commented on B.cpp
>      if (parent == -100) {
-100 плохо зашивать в код
вынести в константу

2019-04-08 11:23 UTC, ibulgakov commented on B.cpp
>              DFS(g, children[i], visited, timeStart, vertex, minLen);
Название

2019-04-08 11:23 UTC, ibulgakov commented on B.cpp
>      int mincycle = amount * 2;
почему amount * 2

2019-04-15 11:32 UTC, ibulgakov requested changes

2019-04-15 11:32 UTC, ibulgakov commented on B.cpp
> +const int PARENT = -100;
UnknownParent

2019-04-15 11:32 UTC, ibulgakov commented on B.cpp
> +const int PARENT = -100;
-1

2019-04-15 11:32 UTC, ibulgakov commented on B.cpp
>              DFS(g, i, visited, time, -100, mincycle);
-100 - убрать константу

2019-04-15 11:32 UTC, ibulgakov commented on B.cpp
> +void DFS(const ListGraph& g, int vertex, vector<colors>& visited, vector<int>& timeStart, int parent, int& minLen) {
FindMinCycle для конкретной вершины.
Должно возвращать true или false

2019-09-02 20:18 UTC, IlyaGusev requested changes
Невозможно проверять, нужно нормально залить

2019-09-03 16:11 UTC, closed without merging